FROM rust:bullseye

# 安装构建依赖
RUN apt-get update && apt-get install -y \
    libgtk-3-dev \
    libssl-dev \
    pkg-config \
    libx11-dev \
    libxcb1-dev \
    libxcb-render0-dev \
    libxcb-shape0-dev \
    libxcb-xfixes0-dev \
    libxkbcommon-dev \
    libwayland-dev \
    && rm -rf /var/lib/apt/lists/*

# 添加目标平台
RUN rustup target add x86_64-unknown-linux-gnu

WORKDIR /app
CMD ["bash", "-c", "RUSTFLAGS='-C target-feature=-crt-static -C link-arg=-Wl,--no-as-needed -C link-arg=-ldl' cargo build --release --target x86_64-unknown-linux-gnu --features file_dialog,vendored-openssl && chown -R $(stat -c '%u:%g' .) /app"]
